affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role
              operator: In
              values:
                - gpu

tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule

gfd:
  enabled: true
